name: "Build kernels for release"

env:
  OUT_DIR: "${{ github.workspace }}/out"

on:
  workflow_call:
    inputs:
      from_ci:
        type: boolean
        required: false
        default: true

  workflow_dispatch:

jobs:
  Set-repos:
    name: "🐂 Parse repos.json"
    runs-on: ubuntu-latest
    outputs:
      repos: ${{ steps.generate-matrix.outputs.repos }}
      builddate: ${{ steps.generate-builddate.outputs.builddate }}
    steps:
      - name: "😄 Checkout"
        uses: actions/checkout@v3

      - name: "😆 Generate Matrix"
        id: generate-matrix
        run: |
          echo "repos<<EOF" >> $GITHUB_OUTPUT
          jq -s '[.[][]]' repos/repos*.json >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: "⏰ Set builddate"
        id: generate-builddate
        run: echo "builddate=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

  Build-Kernel:
    name: "🐎 Build kernel"
    runs-on: ubuntu-latest
    needs:
      - Set-repos
    strategy:
      fail-fast: false
      matrix:
        repos: ${{ fromJSON(needs.Set-repos.outputs.repos) }}
    env:
      WORKSPACE: ${{ github.workspace }}
      builddate: "${{ needs.Set-repos.outputs.builddate }}"

      KNAME: ${{ matrix.repos.kernelName }}
      KERNEL_DEVICE: ${{ matrix.repos.kernelSource.device }}
      DEFCONFIG_NAME: ${{ matrix.repos.kernelSource.defconfig }}

      withRoot: ${{ matrix.repos.withRoot }}
      withSUSFS: ${{ matrix.repos.withSUSFS }}
      whichSUSFS: ${{ matrix.repos.whichSUSFS }}
      withKPM: ${{ matrix.repos.withKPM }}
      ccache: ${{ matrix.repos.ccache }}
      useAnykernel: ${{ matrix.repos.AnyKernel3.use }}
      release: ${{ matrix.repos.AnyKernel3.release }}

    steps:
      - name: "🟣 Set Kernel Variables"
        run: |
          echo "KERNEL_NAME=${{ matrix.repos.kernelSource.name }}" >> $GITHUB_ENV
          echo "KERNEL_REPO=${{ matrix.repos.kernelSource.repo }}" >> $GITHUB_ENV
          echo "KERNEL_BRANCH=${{ matrix.repos.kernelSource.branch }}" >> $GITHUB_ENV

          echo "toolchains=$(echo '${{ toJSON(matrix.repos.toolchains) }}' | jq -c)" >> $GITHUB_ENV
          echo "params=$(echo '${{ toJSON(matrix.repos.params) }}' | jq -c)" >> $GITHUB_ENV
          echo "THREAD=$(nproc --all)" >> $GITHUB_ENV

      - name: "⭐ Install prerequisites"
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential bc gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev libfl-dev libncursesw5-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev curl git wget zip unzip tar gzip bzip2 ccache

      - name: "🌟 Clone kernel source"
        run: |
          git clone --recursive --depth=1 -j $(nproc) --branch $KERNEL_BRANCH $KERNEL_REPO $KERNEL_NAME
          echo "Kernel commit: $(git -C $KERNEL_NAME rev-parse HEAD)"

      - name: "💫 Get toolchains"
        run: |
          toolchains_num="$(echo $toolchains | jq 'length')"
          for ((i=0;i<toolchains_num;i++)); do
            toolchain_name=$(echo $toolchains | jq -r ".[$i].name")
            toolchain_url=$(echo $toolchains | jq -r ".[$i].url")
            toolchain_repo=$(echo $toolchains | jq -r ".[$i].repo")
            toolchain_branch=$(echo $toolchains | jq -r ".[$i].branch")
            if [ -z "$toolchain_url" ] || [ "$toolchain_url" = "null" ]; then
              git clone --recursive --depth=1 -j $(nproc) --branch $toolchain_branch $toolchain_repo $toolchain_name
            else
              wget "$toolchain_url"
              filename="${toolchain_url##*/}"
              mkdir -p $toolchain_name
              tar xf "$filename" -C $toolchain_name || unzip "$filename" -d $toolchain_name
            fi
            jq -r ".[$i].binPath[] | tostring" <<< "$toolchains" | while read -r bin_path; do
              echo "$WORKSPACE/$toolchain_name/$bin_path" >> $GITHUB_PATH
            done
          done

      - name: "🐳 Enable Docker-required kernel configs"
        working-directory: ${{ env.KERNEL_NAME }}
        run: |
          cat <<EOF > docker_options.cfg
          CONFIG_IPC_NS=y
          CONFIG_USER_NS=y
          CONFIG_POSIX_MQUEUE=y
          CONFIG_KEYS=y
          CONFIG_CGROUP_DEVICE=y
          CONFIG_CGROUP_PIDS=y
          CONFIG_CGROUP_PERF=y
          CONFIG_CGROUP_HUGETLB=y
          CONFIG_BLK_CGROUP=y
          CONFIG_BLK_DEV_THROTTLING=y
          CONFIG_CFQ_GROUP_IOSCHED=y
          CONFIG_CFS_BANDWIDTH=y
          CONFIG_NET_CLS_CGROUP=y
          CONFIG_CGROUP_NET_PRIO=y
          CONFIG_VETH=y
          CONFIG_DUMMY=y
          CONFIG_VXLAN=y
          CONFIG_IPVLAN=y
          CONFIG_MACVLAN=y
          CONFIG_BRIDGE_VLAN_FILTERING=y
          CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y
          CONFIG_NETFILTER_XT_MATCH_IPVS=y
          CONFIG_IP6_NF_NAT=y
          CONFIG_IP6_NF_TARGET_MASQUERADE=y
          CONFIG_NF_TABLES=y
          CONFIG_NFT_CT=y
          CONFIG_NFT_FIB=y
          CONFIG_NFT_FIB_IPV4=y
          CONFIG_NFT_FIB_IPV6=y
          CONFIG_NFT_MASQ=y
          CONFIG_NFT_NAT=y
          CONFIG_IP_VS=y
          CONFIG_IP_VS_NFCT=y
          CONFIG_IP_VS_PROTO_TCP=y
          CONFIG_IP_VS_PROTO_UDP=y
          CONFIG_IP_VS_RR=y
          CONFIG_BTRFS_FS=y
          CONFIG_BTRFS_FS_POSIX_ACL=y
          CONFIG_MEMCG_SWAP=y
          CONFIG_MEMCG_SWAP_ENABLED=y
          CONFIG_ANDROID_PARANOID_NETWORK=n
          EOF

          # Merge options and resolve dependencies
          scripts/kconfig/merge_config.sh -m arch/arm64/configs/${{ env.DEFCONFIG_NAME }} docker_options.cfg
          make olddefconfig

      - name: "🎶 Build kernel"
        working-directory: ${{ env.KERNEL_NAME }}
        env:
          args: ${{ steps.generate-args.outputs.args }}
        run: make ${{ env.args }}

      - name: "❤️ Pack AnyKernel3.zip"
        if: ${{ env.useAnykernel == 'true' }}
        run: |
          cp -f ${{ env.OUT_DIR }}/arch/arm64/boot/Image.gz ./AnyKernel3/
          cd AnyKernel3/
          zip -q -r "${{ env.KERNEL_DEVICE }}-${{ env.KERNEL_NAME }}-${{ env.builddate }}.zip" *

      - name: "💾 Upload AnyKernel3 image"
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.KERNEL_DEVICE }}-${{ env.KERNEL_NAME }}-${{ env.builddate }}"
          path: AnyKernel3/*.zip
